version: "3.8"

services:
  main:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - PRIVATE_KEY=
      - USERNAME=
      - PASSWORD=
